parameters:
    ibw_jobeet_twig_extension.class: Ibw\JobeetBundle\Twig\Extensions\JobeetExtensions 
    ibw_jobeet_paginator.extension: Ibw\JobeetBundle\Twig\Extensions\PaginatorExtension
    ibw_jobeet_paginator.class: Ibw\JobeetBundle\Utils\Paginator
    ibw.jobeet.admin.category.class: Ibw\JobeetBundle\Admin\CategoryAdmin
    ibw.jobeet.admin.job.class: Ibw\JobeetBundle\Admin\JobAdmin
#    ibw.user.provider.class: Ibw\UserBundle\Repository\UserRepository
#    ibw.user.provider.entity.class: Ibw\UserBundle\Entity\User

services:
    ibw_jobeet_twig_extension:
        class: %ibw_jobeet_twig_extension.class%
        tags:
          - { name: twig.extension }
        arguments:
            container:  "@service_container"
            doctrine:   "@doctrine_mongodb"

    ibw_jobeet_twig_paginator_extension:
        class: %ibw_jobeet_paginator.extension%
        tags:
          - { name: twig.extension }
        arguments:
            router: "@router"
            paginator: "@paginator"
        calls:
          - [setRequest, ['@?request=']]

    paginator:
        class: %ibw_jobeet_paginator.class%

#    ibw.jobeet.admin.category:
#        class: %ibw.jobeet.admin.category.class%
#        tags:
#            - { name: sonata.admin, manager_type: odm, group: jobeet, label: Categories }
#        arguments:
#            - ~
#            - Ibw\JobeetBundle\Document\Category
#            - 'IbwJobeetBundle:CategoryAdmin'
#
#    ibw.jobeet.admin.job:
#        class: %ibw.jobeet.admin.job.class%
#        tags:
#            - { name: sonata.admin, manager_type: odm, group: jobeet, label: Jobs }
#        arguments:
#            - ~
#            - Ibw\JobeetBundle\Document\Job
#            - 'IbwJobeetBundle:JobAdmin'

#    ibw.user.provider:
#        class: %ibw.user.provider.class%
#        factory_service: doctrine
#        factory_method: getRepository
#        arguments:
#            - %ibw.user.provider.entity.class%