<?php

namespace Ibw\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    public function getRoleIfExists($role_name)
    {
        $q = $this->createQueryBuilder('r')
                    ->select('r')
                    ->where('r.role = :role')
                    ->setParameter('role', $role_name)
                    ->getQuery();
        try{
            $role = $q->getSingleResult();
        }
        catch(NoResultException $e)
        {
            $role = null;
        }

        return $role;
    }
}
