<?php

namespace Ibw\UserBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ORM\NoResultException;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends DocumentRepository
{
    public function getRoleIfExists($role_name)
    {
        $q = $this->createQueryBuilder()
                    ->field('role')->equals(new \MongoCode($role_name))
                    ->getQuery();
        try{
            $role = $q->getSingleResult();
        }
        catch(NoResultException $e)
        {
            $role = null;
        }

        return $role;
    }
}
