parameters:
#    ibw_user.example.class: Ibw\UserBundle\Example

services:
#    ibw_user.example:
#        class: %ibw_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
